version: '3'

services:
  frontend:
    build:
      context: ../webapp/frontend
      dockerfile: ../../dev/frontend/Dockerfile
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/log:/var/log/nginx
    ports:
      - "8080:80"
    depends_on:
      - backend
  backend:
    build:
      context: ../webapp/go
      dockerfile: ../../dev/go/Dockerfile
    restart: always
    environment:
      MYSQL_HOSTNAME: mysql
      DEBUG: "true"
    entrypoint: dockerize -timeout 60s -wait tcp://mysql:3306
    command: air -c /webapp/go/air.toml
    ports:
      - "7000:7000"
    depends_on:
      - mysql
    volumes:
      - ../webapp/go:/webapp/go:rw
      - ../webapp/data:/webapp/data:ro
      - ../webapp/sql:/webapp/sql:ro
  mysql:
    build:
      context: ./mysql
    platform: linux/x86_64
    restart: always
    # setup.sqlの代替
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: isucon
      MYSQL_PASSWORD: isucon
      MYSQL_DATABASE: isucholar
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
    expose:
      - "3306"
    ports:
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql
      - ./mysql/conf:/etc/mysql/conf.d
      - ./mysql/log:/var/log/mysql
  adminer:
    image: adminer:latest
    restart: always
    environment:
      ADMINER_DEFAULT_SERVER: mysql
      ADMINER_DESIGN: nette
    ports:
      - "7001:8080"

volumes:
  mysql:
